version: '3.9'

services:
  redis:
    image: 'redis:latest'
    ports: ['6379:6379']
    container_name: 'redis'
    env_file:
      - ./.env
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: '0.5'
          memory: 1024M
  backend-api:
    build:
      dockerfile: Dockerfile
    container_name: 'backend-api'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - REDIS_URL=redis://redis:6379
    volumes: ['./:/home/bun/app']
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 512M
        limits:
          cpus: '1'
          memory: 1024M
    links:
      - redis
    depends_on:
      - redis

volumes:
  backend-api:
  redis:
