version: '3.9'

services:
  postgres:
    image: 'postgres:latest'
    ports: ['5432:5432']
    container_name: 'postgres'
    env_file:
      - ./.env
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 512M
        limits:
          cpus: '1'
          memory: 1024M
  redis:
    image: 'redis:latest'
    ports: ['6379:6379']
    container_name: 'redis'
    env_file:
      - ./.env
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 512M
        limits:
          cpus: '1'
          memory: 1024M
  backend-api:
    build:
      dockerfile: Dockerfile
    container_name: 'backend-api'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - REDIS_URL=redis://redis:6379
    volumes: ['./:/home/bun/app']
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 512M
        limits:
          cpus: '1'
          memory: 1024M
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis

volumes:
  backend-api:
  postgres:
  redis:
